---

- name : Install packages without specific configuration
  become: True
  apt :
    name  : "{{ item }}"
    state : present
    update_cache : True
  with_items : "{{ base_packages_simples_list }}"

