---

# Tasks file for base-packages

- name: 'Install base packages on Debian systems'
  become: True
  apt:
    name: "{{ item }}"
    state: 'present'
    update_cache: True
  with_items: "{{ base_packages_list }}"
  when: "{{ (ansible_os_family | lower) == 'debian' }}"
  tags:
    - 'base-packages::role'
    - 'base-packages::install'


- name: 'Install base packages on RedHat systems'
  become: True
  yum:
    name: "{{ item }}"
    state: 'present'
  with_items: "{{ base_packages_list }}"
  when: "{{ (ansible_os_family | lower) == 'redhat' }}"
  tags:
    - 'base-packages::role'
    - 'base-packages::install'
