---

# Tasks file for base-packages

- name: Load the OS specific varibles
  include_vars: "{{ role_path }}/vars/{{ ansible_os_family }}.yml"
  when:
    - base_packages_install_enabled
    - not base_packages_list


- include: install_debian.yml
  tags:
    - install
  when: ansible_os_family == "Debian"

