---

# Main tasks file for base-packages role

- name: 'INIT | Manage variables to use for our target'
  include: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::base-packages'
    - 'role::base-packages::init'


- name: 'Install base packages on Debian systems'
  become: True
  apt:
    name: "{{ item }}"
    state: 'present'
    update_cache: True
  with_items: "{{ base_packages_list }}"
  when: "{{ (ansible_os_family | lower) == 'debian' }}"
  tags:
    - 'base-packages::role'
    - 'base-packages::install'


- name: 'Install base packages on RedHat systems'
  become: True
  yum:
    name: "{{ item }}"
    state: 'present'
  with_items: "{{ base_packages_list }}"
  when: "{{ (ansible_os_family | lower) == 'redhat' }}"
  tags:
    - 'base-packages::role'
    - 'base-packages::install'
